import { act, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { useState } from 'react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import * as api from '../api';
import type { Session } from '../api';
import { TerminalPane } from '../components/TerminalPane';
import { TerminalTabs } from '../components/TerminalTabs';

const terminalState = vi.hoisted(() => ({
  instances: [] as Array<{
    write: ReturnType<typeof vi.fn>;
    writeln: ReturnType<typeof vi.fn>;
    emitData: (data: string) => void;
    attachCustomKeyEventHandler: ReturnType<typeof vi.fn>;
    dispose: ReturnType<typeof vi.fn>;
  }>,
}));

const webSocketState = vi.hoisted(() => ({
  instances: [] as Array<{
    send: ReturnType<typeof vi.fn>;
    close: ReturnType<typeof vi.fn>;
    addEventListener: ReturnType<typeof vi.fn>;
    emit: (type: string, event?: unknown) => void;
  }>,
}));

const searchAddonState = vi.hoisted(() => ({
  instances: [] as Array<{
    findNext: ReturnType<typeof vi.fn>;
    findPrevious: ReturnType<typeof vi.fn>;
    clearDecorations: ReturnType<typeof vi.fn>;
  }>,
}));

const resizeObserverState = vi.hoisted(() => ({
  instances: [] as Array<{
    observe: ReturnType<typeof vi.fn>;
    disconnect: ReturnType<typeof vi.fn>;
    trigger: () => void;
  }>,
}));

vi.mock('../api', () => ({
  listSessionOutput: vi.fn(),
  listSnippets: vi.fn(() => Promise.resolve([])),
}));

vi.mock('xterm', () => ({
  Terminal: vi.fn().mockImplementation(function () {
    const dataHandlers: Array<(data: string) => void> = [];
    const terminal = {
      cols: 80,
      rows: 24,
      loadAddon: vi.fn(),
      open: vi.fn(),
      write: vi.fn((data: string, callback?: () => void) => {
        if (data.includes('\x1b[c')) {
          dataHandlers.forEach((handler) => handler('\x1b[?1;2c'));
        }
        callback?.();
      }),
      writeln: vi.fn(),
      onData: vi.fn((handler: (data: string) => void) => {
        dataHandlers.push(handler);
        return { dispose: vi.fn() };
      }),
      emitData: (data: string) => dataHandlers.forEach((handler) => handler(data)),
      attachCustomKeyEventHandler: vi.fn(),
      dispose: vi.fn(),
    };
    terminalState.instances.push(terminal);
    return terminal;
  }),
}));

vi.mock('xterm-addon-fit', () => ({
  FitAddon: vi.fn().mockImplementation(function () {
    return { fit: vi.fn() };
  }),
}));

vi.mock('xterm-addon-search', () => ({
  SearchAddon: vi.fn().mockImplementation(function () {
    const instance = {
      findNext: vi.fn(),
      findPrevious: vi.fn(),
      clearDecorations: vi.fn(),
    };
    searchAddonState.instances.push(instance);
    return instance;
  }),
}));

const mockedApi = vi.mocked(api);

beforeEach(() => {
  terminalState.instances.length = 0;
  webSocketState.instances.length = 0;
  searchAddonState.instances.length = 0;
  resizeObserverState.instances.length = 0;
  class FakeWebSocket {
    static OPEN = 1;
    readyState = FakeWebSocket.OPEN;
    send = vi.fn();
    close = vi.fn();
    listeners = new Map<string, Array<(event: unknown) => void>>();
    addEventListener = vi.fn((type: string, listener: (event: unknown) => void) => {
      const current = this.listeners.get(type) ?? [];
      current.push(listener);
      this.listeners.set(type, current);
    });
    emit(type: string, event?: unknown) {
      for (const listener of this.listeners.get(type) ?? []) {
        listener(event);
      }
    }

    constructor() {
      webSocketState.instances.push(this);
    }
  }
  vi.stubGlobal('WebSocket', FakeWebSocket);
  class FakeResizeObserver {
    observe = vi.fn();
    unobserve = vi.fn();
    disconnect = vi.fn();

    constructor(private readonly callback: ResizeObserverCallback) {
      resizeObserverState.instances.push({
        observe: this.observe,
        disconnect: this.disconnect,
        trigger: () => this.callback([], this),
      });
    }
  }
  vi.stubGlobal('ResizeObserver', FakeResizeObserver);
  vi.clearAllMocks();
});

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('TerminalPane', () => {
  it('restores persisted output when opening an existing session', async () => {
    mockedApi.listSessionOutput.mockResolvedValue([
      {
        id: 'chunk-1',
        session_id: 'sess-1',
        start_seq: 1,
        end_seq: 1,
        data: 'Claude prompt\r\n',
      },
    ]);

    render(<TerminalPane sessionId="sess-1" readOnly={false} />);

    await waitFor(() => expect(mockedApi.listSessionOutput).toHaveBeenCalledWith('sess-1'));
    await waitFor(() => expect(terminalState.instances[0].write.mock.calls[0]?.[0]).toBe('Claude prompt\r\n'));
  });

  it('does not send terminal responses generated by restored output back to the pty', async () => {
    let resolveOutput: (chunks: Awaited<ReturnType<typeof api.listSessionOutput>>) => void = () => undefined;
    mockedApi.listSessionOutput.mockReturnValue(new Promise((resolve) => {
      resolveOutput = resolve;
    }));

    render(<TerminalPane sessionId="sess-1" readOnly={false} />);

    await waitFor(() => expect(webSocketState.instances.length).toBe(1));
    resolveOutput([
      {
        id: 'chunk-1',
        session_id: 'sess-1',
        start_seq: 1,
        end_seq: 1,
        data: 'Claude asks terminal\x1b[c',
      },
    ]);

    await waitFor(() => expect(terminalState.instances[0].write.mock.calls[0]?.[0]).toBe('Claude asks terminal\x1b[c'));
    const sentMessages = webSocketState.instances[0].send.mock.calls.map(([message]) => String(message));
    expect(sentMessages.some((message) => message.includes('stdin') && message.includes('1;2c'))).toBe(false);
  });

  it('does not flush pending stdout after the pane unmounts during restore', async () => {
    let resolveOutput: (chunks: Awaited<ReturnType<typeof api.listSessionOutput>>) => void = () => undefined;
    mockedApi.listSessionOutput.mockReturnValue(new Promise((resolve) => {
      resolveOutput = resolve;
    }));

    const { unmount } = render(<TerminalPane sessionId="sess-1" readOnly={false} />);
    await waitFor(() => expect(webSocketState.instances.length).toBe(1));

    webSocketState.instances[0].emit('message', {
      data: JSON.stringify({
        type: 'stdout',
        session_id: 'sess-1',
        payload: { seq: 2, data: 'late output' },
      }),
    });
    unmount();
    resolveOutput([]);

    await new Promise((resolve) => setTimeout(resolve, 0));
    expect(terminalState.instances[0].write).not.toHaveBeenCalledWith('late output', expect.any(Function));
  });

  it('does not show a connection closed message when switching sessions', async () => {
    mockedApi.listSessionOutput.mockResolvedValue([]);

    const { rerender } = render(<TerminalPane sessionId="sess-1" readOnly={false} />);
    await waitFor(() => expect(webSocketState.instances.length).toBe(1));
    const oldSocket = webSocketState.instances[0];

    rerender(<TerminalPane sessionId="sess-2" readOnly={false} />);
    await waitFor(() => expect(webSocketState.instances.length).toBe(2));

    oldSocket.emit('close');

    await new Promise((resolve) => setTimeout(resolve, 0));
    expect(screen.queryByRole('status')).not.toBeInTheDocument();
  });

  it('updates the tab status when the websocket reports session state', async () => {
    mockedApi.listSessionOutput.mockResolvedValue([]);

    function TerminalTabsHost() {
      const [sessions, setSessions] = useState<Session[]>([
        { id: 'sess-1', title: 'bash', status: 'running', working_directory: '/tmp/project' },
      ]);
      return (
        <TerminalTabs
          sessions={sessions}
          onSessionsChange={setSessions}
          onCloseSession={vi.fn()}
          onRenameSession={vi.fn()}
        />
      );
    }

    render(<TerminalTabsHost />);

    await waitFor(() => expect(webSocketState.instances.length).toBe(1));
    expect(screen.getByText('running')).toHaveClass('statusRunning');

    webSocketState.instances[0].emit('message', {
      data: JSON.stringify({
        type: 'session_state',
        session_id: 'sess-1',
        payload: { session_id: 'sess-1', status: 'exited', message: 'exited' },
      }),
    });

    expect(await screen.findByText('exited')).toHaveClass('statusExited');
    expect(screen.queryByText('running')).not.toBeInTheDocument();
  });

  it('sends resize when the terminal container changes size', async () => {
    mockedApi.listSessionOutput.mockResolvedValue([]);

    render(<TerminalPane sessionId="sess-1" readOnly={false} />);

    await waitFor(() => expect(webSocketState.instances.length).toBe(1));
    webSocketState.instances[0].emit('open');
    webSocketState.instances[0].send.mockClear();
    resizeObserverState.instances[0].trigger();

    await waitFor(() => expect(webSocketState.instances[0].send).toHaveBeenCalled());
    const sentMessages = webSocketState.instances[0].send.mock.calls.map(([message]) => String(message));
    expect(sentMessages.some((message) => message.includes('"type":"resize"') && message.includes('"session_id":"sess-1"'))).toBe(true);
  });

  it('shows websocket error messages in the terminal pane', async () => {
    mockedApi.listSessionOutput.mockResolvedValue([]);

    render(<TerminalPane sessionId="sess-1" readOnly={false} />);

    await waitFor(() => expect(webSocketState.instances.length).toBe(1));
    webSocketState.instances[0].emit('message', {
      data: JSON.stringify({
        type: 'error',
        payload: { code: 'agent_unavailable', message: 'agent disconnected' },
      }),
    });

    expect(await screen.findByRole('status')).toHaveTextContent('agent disconnected');
  });

  it('opens search from the toolbar button and forwards queries to the addon', async () => {
    mockedApi.listSessionOutput.mockResolvedValue([]);
    render(<TerminalPane sessionId="sess-1" readOnly={false} />);
    await userEvent.click(screen.getByRole('button', { name: /search terminal output/i }));
    const input = screen.getByLabelText('Search terminal');
    await userEvent.type(input, 'panic{Enter}');
    const addon = searchAddonState.instances[searchAddonState.instances.length - 1];
    expect(addon?.findNext).toHaveBeenCalledWith('panic', expect.objectContaining({ caseSensitive: false }));
    await userEvent.type(input, '{Escape}');
    expect(addon?.clearDecorations).toHaveBeenCalled();
  });

  it('opens search and prevents the native find dialog on Ctrl+F', async () => {
    mockedApi.listSessionOutput.mockResolvedValue([]);
    render(<TerminalPane sessionId="sess-1" readOnly={false} />);
    const handler = terminalState.instances[0].attachCustomKeyEventHandler.mock.calls[0]?.[0] as (
      event: { type: string; ctrlKey: boolean; metaKey: boolean; key: string; preventDefault: () => void },
    ) => boolean;
    const preventDefault = vi.fn();
    let result = true;
    act(() => {
      result = handler({ type: 'keydown', ctrlKey: true, metaKey: false, key: 'f', preventDefault });
    });
    expect(result).toBe(false);
    expect(preventDefault).toHaveBeenCalled();
    expect(screen.getByLabelText('Search terminal')).toBeInTheDocument();
  });

  it('sends snippet text through the session socket via the imperative handle', async () => {
    mockedApi.listSessionOutput.mockResolvedValue([]);
    const ref = { current: null as null | { sendText: (text: string) => void } };
    render(<TerminalPane ref={ref} sessionId="sess-1" readOnly={false} />);
    await waitFor(() => expect(ref.current).not.toBeNull());
    const socket = webSocketState.instances[webSocketState.instances.length - 1];
    ref.current?.sendText('df -h');
    expect(socket?.send).toHaveBeenCalledWith(
      JSON.stringify({ type: 'stdin', session_id: 'sess-1', payload: { session_id: 'sess-1', data: 'df -h' } })
    );
  });
});
