import { render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import * as api from '../api';
import { TerminalPane } from '../components/TerminalPane';

const terminalState = vi.hoisted(() => ({
  instances: [] as Array<{
    write: ReturnType<typeof vi.fn>;
    writeln: ReturnType<typeof vi.fn>;
    emitData: (data: string) => void;
    dispose: ReturnType<typeof vi.fn>;
  }>,
}));

const webSocketState = vi.hoisted(() => ({
  instances: [] as Array<{
    send: ReturnType<typeof vi.fn>;
    close: ReturnType<typeof vi.fn>;
    addEventListener: ReturnType<typeof vi.fn>;
    emit: (type: string, event?: unknown) => void;
  }>,
}));

const resizeObserverState = vi.hoisted(() => ({
  instances: [] as Array<{
    observe: ReturnType<typeof vi.fn>;
    disconnect: ReturnType<typeof vi.fn>;
    trigger: () => void;
  }>,
}));

vi.mock('../api', () => ({
  listSessionOutput: vi.fn(),
}));

vi.mock('xterm', () => ({
  Terminal: vi.fn().mockImplementation(function () {
    const dataHandlers: Array<(data: string) => void> = [];
    const terminal = {
      cols: 80,
      rows: 24,
      loadAddon: vi.fn(),
      open: vi.fn(),
      write: vi.fn((data: string, callback?: () => void) => {
        if (data.includes('\x1b[c')) {
          dataHandlers.forEach((handler) => handler('\x1b[?1;2c'));
        }
        callback?.();
      }),
      writeln: vi.fn(),
      onData: vi.fn((handler: (data: string) => void) => {
        dataHandlers.push(handler);
        return { dispose: vi.fn() };
      }),
      emitData: (data: string) => dataHandlers.forEach((handler) => handler(data)),
      dispose: vi.fn(),
    };
    terminalState.instances.push(terminal);
    return terminal;
  }),
}));

vi.mock('xterm-addon-fit', () => ({
  FitAddon: vi.fn().mockImplementation(function () {
    return { fit: vi.fn() };
  }),
}));

const mockedApi = vi.mocked(api);

beforeEach(() => {
  terminalState.instances.length = 0;
  webSocketState.instances.length = 0;
  resizeObserverState.instances.length = 0;
  class FakeWebSocket {
    static OPEN = 1;
    readyState = FakeWebSocket.OPEN;
    send = vi.fn();
    close = vi.fn();
    listeners = new Map<string, Array<(event: unknown) => void>>();
    addEventListener = vi.fn((type: string, listener: (event: unknown) => void) => {
      const current = this.listeners.get(type) ?? [];
      current.push(listener);
      this.listeners.set(type, current);
    });
    emit(type: string, event?: unknown) {
      for (const listener of this.listeners.get(type) ?? []) {
        listener(event);
      }
    }

    constructor() {
      webSocketState.instances.push(this);
    }
  }
  vi.stubGlobal('WebSocket', FakeWebSocket);
  class FakeResizeObserver {
    observe = vi.fn();
    unobserve = vi.fn();
    disconnect = vi.fn();

    constructor(private readonly callback: ResizeObserverCallback) {
      resizeObserverState.instances.push({
        observe: this.observe,
        disconnect: this.disconnect,
        trigger: () => this.callback([], this),
      });
    }
  }
  vi.stubGlobal('ResizeObserver', FakeResizeObserver);
  vi.clearAllMocks();
});

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('TerminalPane', () => {
  it('restores persisted output when opening an existing session', async () => {
    mockedApi.listSessionOutput.mockResolvedValue([
      {
        id: 'chunk-1',
        session_id: 'sess-1',
        start_seq: 1,
        end_seq: 1,
        data: 'Claude prompt\r\n',
      },
    ]);

    render(<TerminalPane sessionId="sess-1" readOnly={false} />);

    await waitFor(() => expect(mockedApi.listSessionOutput).toHaveBeenCalledWith('sess-1'));
    await waitFor(() => expect(terminalState.instances[0].write.mock.calls[0]?.[0]).toBe('Claude prompt\r\n'));
  });

  it('does not send terminal responses generated by restored output back to the pty', async () => {
    let resolveOutput: (chunks: Awaited<ReturnType<typeof api.listSessionOutput>>) => void = () => undefined;
    mockedApi.listSessionOutput.mockReturnValue(new Promise((resolve) => {
      resolveOutput = resolve;
    }));

    render(<TerminalPane sessionId="sess-1" readOnly={false} />);

    await waitFor(() => expect(webSocketState.instances.length).toBe(1));
    resolveOutput([
      {
        id: 'chunk-1',
        session_id: 'sess-1',
        start_seq: 1,
        end_seq: 1,
        data: 'Claude asks terminal\x1b[c',
      },
    ]);

    await waitFor(() => expect(terminalState.instances[0].write.mock.calls[0]?.[0]).toBe('Claude asks terminal\x1b[c'));
    const sentMessages = webSocketState.instances[0].send.mock.calls.map(([message]) => String(message));
    expect(sentMessages.some((message) => message.includes('stdin') && message.includes('1;2c'))).toBe(false);
  });

  it('does not flush pending stdout after the pane unmounts during restore', async () => {
    let resolveOutput: (chunks: Awaited<ReturnType<typeof api.listSessionOutput>>) => void = () => undefined;
    mockedApi.listSessionOutput.mockReturnValue(new Promise((resolve) => {
      resolveOutput = resolve;
    }));

    const { unmount } = render(<TerminalPane sessionId="sess-1" readOnly={false} />);
    await waitFor(() => expect(webSocketState.instances.length).toBe(1));

    webSocketState.instances[0].emit('message', {
      data: JSON.stringify({
        type: 'stdout',
        session_id: 'sess-1',
        payload: { seq: 2, data: 'late output' },
      }),
    });
    unmount();
    resolveOutput([]);

    await new Promise((resolve) => setTimeout(resolve, 0));
    expect(terminalState.instances[0].write).not.toHaveBeenCalledWith('late output', expect.any(Function));
  });

  it('sends resize when the terminal container changes size', async () => {
    mockedApi.listSessionOutput.mockResolvedValue([]);

    render(<TerminalPane sessionId="sess-1" readOnly={false} />);

    await waitFor(() => expect(webSocketState.instances.length).toBe(1));
    webSocketState.instances[0].emit('open');
    webSocketState.instances[0].send.mockClear();
    resizeObserverState.instances[0].trigger();

    await waitFor(() => expect(webSocketState.instances[0].send).toHaveBeenCalled());
    const sentMessages = webSocketState.instances[0].send.mock.calls.map(([message]) => String(message));
    expect(sentMessages.some((message) => message.includes('"type":"resize"') && message.includes('"session_id":"sess-1"'))).toBe(true);
  });

  it('shows websocket error messages in the terminal pane', async () => {
    mockedApi.listSessionOutput.mockResolvedValue([]);

    render(<TerminalPane sessionId="sess-1" readOnly={false} />);

    await waitFor(() => expect(webSocketState.instances.length).toBe(1));
    webSocketState.instances[0].emit('message', {
      data: JSON.stringify({
        type: 'error',
        payload: { code: 'agent_unavailable', message: 'agent disconnected' },
      }),
    });

    expect(await screen.findByRole('status')).toHaveTextContent('agent disconnected');
  });
});
